services:
  - type: web
    name: qarz-bot
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
